# Generated by Django 3.2 on 2021-06-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantype',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
